COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://flaskuser:Rostukosa2006_@database-1.chco8kus8b77.eu-north-1.rds.amazonaws.com/lab4'

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://flaskuser:Rostukosa2006_@database-1.chco8kus8b77.eu-north-1.rds.amazonaws.com/lab4'

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: admin
  MYSQL_ROOT_PASSWORD: Rostukosa2006_
